version: '3'

vars:
  VERSION: 0.0.1
  LDFLAGS: -X 'codeberg.org/whou/simpleutils/coreutils.Version={{.VERSION}}'

tasks:
  build:
    desc: Builds every utility on the `build` directory.
    cmds:
      - mkdir -p build
      - task: build-util
        vars: 
          UTIL: cat
      
      - task: build-util
        vars: 
          UTIL: dirname
      
      - task: build-util
        vars: 
          UTIL: false
      
      - task: build-util
        vars: 
          UTIL: mkdir
      
      - task: build-util
        vars: 
          UTIL: printenv
      
      - task: build-util
        vars: 
          UTIL: pwd
      
      - task: build-util
        vars: 
          UTIL: rmdir
      
      - task: build-util
        vars: 
          UTIL: touch
      
      - task: build-util
        vars: 
          UTIL: true
      
      - task: build-util
        vars: 
          UTIL: whoami
  
  build-util:
    internal: true
    cmds:
      - go build -o build/{{.UTIL}} -ldflags="{{.LDFLAGS}}" ./coreutils/{{.UTIL}}/{{.UTIL}}.go

  test:
    desc: Runs every utility test.
    cmds:
      - go test ./coreutils/...
      - go test ./internal/...
  
  run:
    desc: "Run a defined utility on the `UTIL` environment variable using `go run`. Example: `task run UTIL=cat -- --help`"
    cmds:
      - go run ./coreutils/{{.UTIL}}/{{.UTIL}}.go {{.CLI_ARGS}}
