version: '3'

vars:
  VERSION: 0.0.1
  LDFLAGS: -X 'codeberg.org/whou/simpleutils/coreutils.Version={{.VERSION}}'

tasks:
  build:
    cmds:
      - mkdir -p build
      - go build -o build/cat -ldflags="{{.LDFLAGS}}" ./coreutils/cat/cat.go
      - go build -o build/dirname -ldflags="{{.LDFLAGS}}" ./coreutils/dirname/dirname.go
      - go build -o build/pwd -ldflags="{{.LDFLAGS}}" ./coreutils/pwd/pwd.go
      - go build -o build/rmdir -ldflags="{{.LDFLAGS}}" ./coreutils/rmdir/rmdir.go
      - go build -o build/whoami -ldflags="{{.LDFLAGS}}" ./coreutils/whoami/whoami.go
