name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: go get .

      - name: Build core utilities
        run: make VERSION="$GITHUB_SHA"
      
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: simpleutils-linux
          path: build
