name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-latest,
              package_suffix: "linux"
            }
          - {
              os: windows-latest, 
              package_suffix: "windows"
            }

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      
      - name: Install build dependencies
        if: ${{ runner.os == 'Windows' }}
        run: choco install -y make

      - name: Build core utilities
        shell: bash
        run: make VERSION="$(git rev-parse --short HEAD)"
      
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: simpleutils-${{ matrix.config.package_suffix }}
          path: build
